# Generated by Django 6.1 on 2026-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_userroomcard_alter_room_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AddField(
            model_name="room",
            name="user",
            field=models.ManyToManyField(to="chat.userroomcard"),
        ),
    ]
