# Generated by Django 6.1.1 on 2026-09-03 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_membership_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoMessage",
            fields=[
                (
                    "message_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chat.message",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
            ],
            bases=("chat.message",),
        ),
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="created_at",
        ),
        migrations.AddField(
            model_name="membership",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="joined_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(default="", max_length=250),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("phone", models.IntegerField()),
                ("show_phone", models.BooleanField(default=True)),
                ("living_place", models.CharField(max_length=50)),
                ("bio", models.TextField(max_length=250)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
