# Generated by Django 6.1.1 on 2026-09-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_photomessage_rename_name_room_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.profile",
            ),
        ),
    ]
