# Generated by Django 6.1.1 on 2026-09-03 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_message_user_message_is_changed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(
                blank=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="profile",
            name="living_place",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
