# Generated by Django 6.1.1 on 2026-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_profile_age_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="number_joined",
            field=models.IntegerField(default=0),
        ),
    ]
