# Generated by Django 6.1.1 on 2026-09-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_room_number_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="number_joined",
        ),
    ]
