# Generated by Django 6.1.1 on 2026-09-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_membership_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="chat.room",
            ),
        ),
    ]
