# Generated by Django 6.1.1 on 2026-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_room_code_alter_membership_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
